### ISSUE TITLE
Example job.json files

### ISSUE THREAD

**Issue by cbravo135** [JeffersonLab/hps-mc#174]
Add a library of job.json files to be used for 2019 MC production.

**Comment by JeremyMcCormick** [comment]
Since running full productions requires more than just a single job.json file, maybe we should have a directory organization like:

[run] / [sample]

e.g.

PhysicsRun2019 / tritrig
Physics Run2019 / aprime
etc.

where all the necessary scripts and files were kept in source control in the sub-directories.

These additional files could include:

- job.json for the sample
- Scripts for generating the full, expanded workflow JSON files
- Full workflow in JSON format (defining all the jobs)
- Scripts for submitting the workflows to batch
- Cleanup scripts
- hps-mc config files pointing to the tools used
- Other supplementary files and scripts

Maybe it would best be done in a separate repository rather than in hps-mc to keep things cleaner.

I'm just not sure how useful having sample job files is without all the other necessary bits, too, at least for running full productions.

**Comment by JeremyMcCormick** [comment]
There are many examples in the `hps-mc/examples` dir now.
